### ISSUE TITLE
crash-reports Stupid Things-1.10.2-1.1.jar

### ISSUE THREAD

**Issue by le10077** [Furgl/Stupid-Things#1]
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.sonicether.soundphysics.SoundPhysics.calculateEntitySoundOffset(SoundPhysics.java:219)
	at net.minecraft.entity.Entity.func_184185_a(Entity.java:972)
	at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1204)
	at furgl.stupidThings.common.entity.EntityThrowable.func_180430_e(EntityThrowable.java:41)
	at net.minecraft.block.Block.func_180658_a(Block.java:807)
	at net.minecraft.entity.Entity.func_184231_a(Entity.java:1007)
	at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:205)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:795)
	at furgl.stupidThings.common.entity.EntityThrowable.func_70071_h_(EntityThrowable.java:56)
	at furgl.stupidThings.common.entity.EntityBalloon.func_70071_h_(EntityBalloon.java:134)
	at furgl.stupidThings.common.entity.EntityBalloonLiquid.func_70071_h_(EntityBalloonLiquid.java:56)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Furgl** [comment]
This was caused by a compatibility issue with the Sound Physics mods. I've fixed this in the attached version and I'll have it fixed for the next public update. Thank you for bringing it to my attention!
[Stupid Things-1.10.2-1.1-Fix.jar.zip](https://github.com/Furgl/Stupid-Things/files/1075503/Stupid.Things-1.10.2-1.1-Fix.jar.zip)

**Comment by le10077** [comment]
thank you!!
