### ISSUE TITLE
Game crashes when i add this mod to my modpack.

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [Furgl/Stupid-Things#20]
And i managed to located the conflict:
i18nUpdate mod that has something to do with block names

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2020-03-01 21:42:50 CST
Description: Initializing game

java.lang.NullPointerException
    at furgl.stupidThings.common.fluid.ModFluids$RegistrationHandler.registerItems(ModFluids.java:68)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1297_RegistrationHandler_registerItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at farseek.world.gen.structure.package$.post(package.scala:38)
    at farseek.world.gen.structure.package.post(package.scala)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by BecksIsAlreadyTaken** [comment]
seems like something with acid registration name ?

**Comment by BecksIsAlreadyTaken** [comment]
somehow i18nupdate mod even translate my config files like this:

    # Should this be enabled?
    B:"World's Smallest Violin"=true

    # Should this be enabled?
    B:橡胶=true

    # Should this be enabled?
    B:温度调节器=true

    # Should this be enabled?
    B:酸液=false

and i turn the last one to false and it goes well.

**Comment by SeraphJACK** [comment]
Nope, it's not I18nUpdateMod's fault. Please close this and move to #21 for further contacts.
